openapi: 3.0.0

info:
  title: OneApp Backend server
  description: This is the first version of OneApp
  version: 0.0.1

servers:
  - url: http://localhost:4000/
    description: LOCALHOST
  - url: http://localhost:5000/
    description: DONT USE

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer  

paths:
  /home:
    summary: Go to Home page
    description: >
      Health check
    get:
      responses: 
        '200':
          description: OK
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  responses: 
                    type: string

  /get/insta:
    get:
      summary: Get instagram data
      responses: 
        '200': 
          desciption: OK
          content: 
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items: 
                      type: object
                      properties: 
                        name: 
                          type: string
                        followers:
                          type: integer
                        follows:
                          type: integer                    
                  date: 
                    type: string
                        
                    
                    

                
                