openapi: 3.0.0

info:
  title: OneApp Backend server
  description: This is the first version of OneApp
  version: 0.0.1

servers:
  - url: http://localhost:4000/
    description: LOCALHOST
  - url: http://localhost:5000/
    description: DONT USE

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer  