openapi: 3.0.0

info:
  title: OneApp Backend server
  description: This is the first version of OneApp
  version: 0.0.1

servers:
  - url: "{protocol}://localhost:4000/"
    description: LOCALHOST
    variables:
      protocol: 
        enum:
          - http
          - https
        default: http
  - url: http://localhost:5000/
    description: DONT USE

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer  

paths:
  /home:
    get:
      tags:
        - Home
      summary: Go to Home page
      description: Health check
      responses: 
        '200':
          description: OK
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  responses: 
                    type: string

  /get/insta:
    get:
      tags:
        - Get Data
      summary: Get instagram data
      responses: 
        '200': 
          desciption: OK
          content: 
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items: 
                      type: object
                      properties: 
                        name: 
                          type: string
                        followers:
                          type: integer
                        follows:
                          type: integer                    
                  date: 
                    type: string
                        
  /get/data/{id}:
    get:
      tags:
        - Get Data
      summary: Get data for debugging purposes
      parameters: 
        - name: id
          in: path
          description: data id
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200': 
          descrpition: OK
          content: 
            applications/json:
              schema:
                type: object
                properties:
                  data: 
                    type: string
                    

                
                